import '../app/globals.css';
import { Inter } from 'next/font/google';
import NavBar from '@/components/NavBar';
import Footer from '@/components/Footer';

const inter = Inter({ subsets: [ 'latin' ] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <main
      style={{ height: '100vh' }}
      className={'flex-col justify-between flex'}
    >
      <NavBar/>
      <div className={'flex-1'}>
        {children}
      </div>
      <Footer/>
    </main>
  );
}
